### ISSUE TITLE
FredBoat bot example usage not cited

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#17]
Defect: "Dscirdo authenication" page uses FredBoat as an example. FredBoat is not properly cited, and should be as the
FredBoat bot is under copyright protection. It is highly recommended this is fixed before filing this software
artifact, as this (while highly unlikely) may be viewed in the future as copyright infringement.

Location of defect: "Dscirdo authenication" page

Recommended Fix: I recommend using a fake mockup example, or editing out any fields using the FredBoat logo or name. Alternatively, the bot could be cited properly.

Criticality: Moderate

**Comment by Mark-Reichert** [comment]
We will look into this thanks.
