### ISSUE TITLE
Improper spelling on "Dscirdo authetication" label

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#18]
Defect: The "Dscirdo authenication" label is spelled incorrectly.

Location: The "Dscirdo authenication" page

Recommend fix: change "Dscirdo authenication" to "Discord Authentication"

Criticality: Low

**Comment by Mark-Reichert** [comment]
This is a non-issue.
