### ISSUE TITLE
"Log In" Methods: Strange Wording

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#24]
Defect: The wording leads to the belief that there are 3 separate options for signing in and authenticating on the webpage ( via Google, Discord, or a local account provided by the website (Username - Password) ), which I don't believe is the case.

Location: Navigation Tab Page | "Log In" Section

Recommended Fix: Remove the "Username, Password, and Forgot Password" parts.

Criticality: Medium

**Comment by Mark-Reichert** [comment]
Issue has been resolved.
