### ISSUE TITLE
"Landing Page": Missing Feature/Label

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#25]
Defect: There is no indication of which page of the 4 is the landing page when the site is first accessed. 

Location: Navigation Tab Page

Recommended Fix:  Determining and clarifying which one of the 4 pages will be the 'homepage"/"landing page" for the website.

Criticality: Low

**Comment by Mark-Reichert** [comment]
This is a non-issue thanks
