### ISSUE TITLE
"Priority Rating Chart": Improved Clarity

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#27]
Defect: Poor readability of the Priority Rating Chart, due to the chart not being sorted by the important value, Priority Rating, by increasing or decreasing order.

Location: "Priority Rating Chart"

Recommended Fix: Sort the chart in decreasing order of "Priority Rating" instead of the arbitrary number 1-8 number way it currently is sorted.

Criticality: Moderate

**Comment by RockinJim** [comment]
This is considered a non-issue for the usability team. We have this data stored in a spreadsheet if we needed to sort it at any point. It is in the order that it is because it follows the same format as the user stories below it (US 1-8). Thanks!
