### ISSUE TITLE
"Priority Rating for Feature 9": Missing 'Feature 9' Rating

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#28]
Defect: Missing Feature 9 on the Priority Rating Chart.

Location: "Priority Rating Chart"

Recommended Fix: Take a quick poll and determine Feature 9's priority and add it to the appropriate spot on the chart.

Criticality: Moderate

**Comment by RockinJim** [comment]
All set! The document now reflects the correct amount of user stories (US 1-8). US #9 was eliminated from the document. Thank you! Thank you for the recommendation!
