### ISSUE TITLE
"Authenticated Users": Vagueness Surrounding Term

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#29]
Defect: Vague term, "Authenticated User", being used. I, as a reader, am currently unaware of what makes someone authenticated and how and if they will be displayed differently: elaborating on this issue will help differentiate Feature 2 and Feature 5. 

Location:  Feature 5 Description

Recommended Fix: Elaborate on the importance and definition of an Authenticated user. List some possible solutions on how they would be distinguished between "regular" users.

Criticality: Moderate

**Comment by RockinJim** [comment]
There is vagueness around this requirement. Therefore, this vagueness is reflected in the user stories. At this point, everyone is a "regular" user, and "authenticated" users are "regular" users. This would be a question for stakeholders or requirements. Based on the current iteration of the design this requirement has not been addressed. It may be necessary to get clarification from stakeholders. This is a requirements team issue, not a usability team issue. The requirement to "display posts from authenticated users" was taken directly from the requirements provided by stakeholders and in my understanding has yet to be addressed. I have no solutions at this time but will make sure to address it with my team.
