### ISSUE TITLE
Table of Contents does not hyperlink to sections

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#38]
Problem: Section headers do not hyperlink to individual sections.

Location: Table of Contents

Suggested fix: Use ctrl+k while highlighting the table of contents option. Then, select hyperlink to location in document. Once this is done, the PDF version of the SRS will also hyperlink for ease of use.

Criticality: Low

**Comment by Noah-Henwood** [comment]
hyperlinks added
