### ISSUE TITLE
Introduction lacks a "Introduction" for product

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#39]
Problem: There is no introduction to introduce the product as a whole.

Location: Introduction section

Suggested fix: "Postmarker is a discord bot that locates, records, and displays posts from users. It is (was?) developed for a class at SUNY Oswego to educate a class of CSC and HCI students."

Criticality: Low

**Comment by Noah-Henwood** [comment]
sentence added
