### ISSUE TITLE
SRS document does not credit the writers of this template

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#40]
Problem: This SRS document does not provide credit for the work contributed by the original template writers. Comparing this to the one approved for use by Bastian Tenbergen, I firmly believe that template was used and the credit section was axed. I could be wrong on this, but the SRS looks strikingly similar to the template. (Not to be rude, but you left in the page bottoms 
 "Q:\IRM\PRIVATE\INITIATI\QA|QAPLAN\SRSPLAN.doc 02/08/18" on the bottom of every page)

Location: End of Document

Suggested fix: Insert citation for original template creators

Criticality: Medium

**Comment by Noah-Henwood** [comment]
IEEE. IEEE Std 830-1998 IEEE Recommended Practice for Software Requirements Specifications. IEEE Computer Society, 1998. Obtained via Blackboard
This is the reference to the document template.
the footer on each page has been removed
