### ISSUE TITLE
Version declaration needed in 2.1.1

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#42]
Problem: "The software runs in the latest version of Chrome or Firefox browser on Windows, Linux, and Mac." claims that the software product will run on all future versions of those browsers. Since the SRS document will most likely eventually be static, this claim will most likely  not be true eventually. By placing a specific version, we can be sure  that the software product will match these claims for the foreseeable future.

Location: Section 2.1.1 sentence one

Suggested fix: Add current versions for chrome and firefox

Criticality: Low

**Comment by Noah-Henwood** [comment]
fixed
