### ISSUE TITLE
Sentence revision needed 2.1.1

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#43]
Problem: "The bot will interface with the discord channel, and post information using Discord API and reaction emoji`s id to send it over to the database on open liberty." Is both a run-on sentence as well as "... will interface with the discord channel, ..." declares any given discord channel as "the" discord channel.

Location: Section 2.1.1 sentence two

Suggested fix: Change to "The discord bot will interface with a given
discord channel. It will also post information using Discord API and
 reaction emoji ids to send it over to the database on open liberty."

Criticality: Low

**Comment by Noah-Henwood** [comment]
fixed
