### ISSUE TITLE
Minor grammar issue 2.1.3 "microservices"

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#44]
Problem: "The three main microservice interfaces with each other." incorrectly declares plural microservices

Location: 2.1.3 sentence one

Suggested fix: Change to "The three main microservices interface with each other."

Criticality: Low

**Comment by Noah-Henwood** [comment]
section was changed on Adam's recommendation
