### ISSUE TITLE
Minor clarity needed in section 2.1.3

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#45]
Problem: "The Discord bot will be interfacing with the database loading posts that are reacted to sent and the database will be 
used to display the posts on the web application." This sentence offers minor confusion as to what the sentence is trying to say.

Location: 2.1.3 sentence two

Suggested fix: Change to "The Discord bot will interface with the database to load posts that are reacted to and sent to it. The database will be used to display posts on the web application."

Criticality: Low

**Comment by Noah-Henwood** [comment]
section was changed on Adam's recommendation
