### ISSUE TITLE
Minor grammar issue in section 2.3

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#47]
Problem: "It could be used in the educational discord server, or workspace discord server" declare an educational discord server as "the" educational discord server.

Location: 2.3, bullet #3

Suggested fix: Change to "The discord bot could be used in an educational server or a workspace discord server."

Criticality: Low

**Comment by Noah-Henwood** [comment]
this portion of section 2.3 was removed
