### ISSUE TITLE
Comment not properly identified 2.4.2

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#48]
Problem: "Maybe in the future memory can be written depending on the engine team such as database memory limit or server limit" is not labeled as a note of some kind.

Location: 2.4.2, end of section

Suggested fix: Add a italicized row to the definitions, acronyms, and abbreviations table (1.3). Or add a <note> item to that table. Or delete the comment.

Criticality: Low

**Comment by Noah-Henwood** [comment]
comment removed
