### ISSUE TITLE
Docker not identified or referenced prior

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#49]
Problem: "The Discord Bot will be running on a Docker hosted with Open Liberty." does not have Docker referenced prior.

Location: 3.) FRQ - 2.4), as well as FRQ - 4.7) and FRQ - 4.8)

Suggested fix: Add Docker to the table in section 1.3 and possibly add Docker and its version to the references in section 1.4

Criticality: Low

**Comment by Noah-Henwood** [comment]
docker added to 1.3
