### ISSUE TITLE
CRUD not identified prior

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#50]
Problem: "Database must provide HTTP CRUD APIs for interaction." acronyms do not have prior references in section 1.3

Location: 3.) FRQ - 3.1)

Suggested fix: Add CRUD to list of acronyms in section 1.3 (maybe add HTTP as well?) ((While we know what CRUD is, any given reader of this document may or may not))

Criticality: Low

**Comment by Noah-Henwood** [comment]
crud added to 1.3
