### ISSUE TITLE
FRQ does not belong in FRQ

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#51]
Problem: "The web application shall be formatted for use on a desktop monitor, so smaller screens may have difficulties with usability." contains a FRQ, but also a Capability Constraint.

Location: 3.) FRQ - 4.11)

Suggested fix: Move " smaller screens may have difficulties with usability" to section 2.4.2

Criticality: Low

**Comment by Noah-Henwood** [comment]
frq removed from requirements section. new capabilities constraint added
