### ISSUE TITLE
Sequence diagram loop does not have proper alt condition inside of loop; loops infinitely

### ISSUE THREAD

**Issue by Rawrs64** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#53]
Problem: Loop does not contain a proper alt condition of when the user enters their correct login. Loop may or may not require exit condition.

Location: Sequence Diagram 6.1.2b D2

Suggested fix: Enter a "alt" if/else condition box inside of the loop instead of dividing the loop. Add those conditions as [condition] to top of if/else boxes. In addition, the loop does not cycle back to allowing the user to enter login info. Therefore on a incorrect login message this loop would loop infinitely without prompting the user to enter login info. Assumption: the loop is supposed to break upon user entering correct login details (and accessing the Web Service Interface). Consider adding a break condition at the top of the loop. This would also be under the format of [condition].

Criticality: Medium

**Comment by Noah-Henwood** [comment]
fixed
