### ISSUE TITLE
Data Type in Class Diagram is Plural 6.1.1a

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#54]
Problem: BigInt data type is plural. 

Location: 6.1.1a -> Reactions Section -> messages_discord_ids, authors_discord_id.

Suggested Fix:  BigInts should be changed to singular because there is only one BigInt representing it. Possibly renaming the variable to reduce confusion.

**Comment by Noah-Henwood** [comment]
fixed
