### ISSUE TITLE
Missing Reference for "OpenID Connect Diagram"

### ISSUE THREAD

**Issue by SvenKappeler** [PavlAvstin/OZ-CSC-480-HCI-521-Fall-2022#55]
Problem: The webpage for the OpenID Connect Diagram is referenced under the diagram, however, it is not present in the 1.4 Reference Section.

Location: 1.4 References 

Suggested Fix: Simply add it as a reference in the 1.4 References section of the document.

**Comment by Noah-Henwood** [comment]
reference added
